"""Added TOTP code in User

Revision ID: 16562ae5048b
Revises: 4e37b3a86a89
Create Date: 2023-11-07 17:32:40.935666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16562ae5048b'
down_revision = '4e37b3a86a89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_2fa_setup', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_2fa_setup')

    # ### end Alembic commands ###
